// Product data for search functionality
export const products = [
  "Accessoires pour bain marie led",
  "Acide acétique glacial 1L",
  "Acide acétique glacial 2.5L",
  "Acide Formique AR 98%",
  "Adaptateur plaque-ballon",
  "Agitateur en Verre – Lot de 10",
  "Agitateur magnétique chauffant",
  "Agitateur Magnétique chauffante EISCO",
  "Aiguille aimantée",
  "Aimant 100 x 20 x 10 mm repéré",
  "Aimant en U",
  "Aimants Droits",
  "Alcool éthylique – Ethanol 96",
  "Alcoomètre 0°-100° Nahita",
  "Alimentation AC/DC Fixe KS46610.1231",
  "Alimentation ajustable 300V 3A SPN300-03C",
  "Alimentation Continue Double Sortie LD0611.6",
  "Alimentation Continue Fix MCP S7-1206",
  "Alimentation Continue Réglable F8-1201",
  "Alimentation Continue Régulée LD0200R",
  "Alimentation de Puissance 6214-BIS",
  "Alimentation EVOLUTION R30",
  "Alimentation Réglable S7-1206",
  "Alimentation réglable T303E MCP",
  "Alimentation Stabilisée 6 – 12V",
  "Alimentation Stabilisée 6 – 12V 5A",
  "Alimentation Stabilisée CC CONARD",
  "Alimentation Stabilisée CC LW LABOR",
  "Alimentation Stabilisée DC LW Labor DF1732W",
  "Alimentation Stabilisée MCP 677008",
  "Alimentation Stabilisée UNI-T UTP3315TFL-II",
  "Alimentation Variable 0-30V, 0,3 A",
  "Ampèremètre analogique 0-5A",
  "Ampèremètre Analogique AC/DC",
  "Ampèremètre Analogique KS46610",
  "Ampèremètre Analogique LD0607.3",
  "Ampèremètre Analogique SAM-001",
  "Ampoule à décanter clé en PTFE BORO 1000ml",
  "Ampoule à décanter clé en PTFE BORO 2000ml",
  "Ampoule à décanter clé en PTFE BORO 250ml",
  "Ampoule à décanter clé en PTFE BORO 500ml",
  "Ampoule à décanter clé en verre 500ml",
  "Analyseur de pH / mV / ISE de paillasse à deux canaux de qualité de laboratoire de recherche – HI5222",
  "Anneau avec noix ø 46 mm",
  "Anneau avec noix ø 61 mm",
  "Anneaux de support",
  "Appareil Circulatoire",
  "Appareil De Chute Libre Élève",
  "Appareil de mesure d’oxygène dissous avancé avec sonde polarographique DO – HI6421P",
  "Appareil de mesure de paillasse pH/ORP avancé – HI6221",
  "Armoire à cases – 205",
  "Armoire à cases – 206",
  "Armoire à cases – 207",
  "Armoire à plans – 403",
  "Armoire à plans – AP5T",
  "Armoire à portes coulissantes – APC1",
  "Armoire Basse – 203",
  "Armoire Basse – 204",
  "Armoire basse à rideaux – 204-DLR",
  "Armoire Chimique",
  "Armoire Chimique Basse",
  "Armoire Chimique Compacte",
  "Armoire Chimique Double",
  "Armoire Electrique – AE",
  "Armoire Forte – ESCUDO 100",
  "Armoire Forte – ESCUDO 45",
  "Armoire Forte – ESCUDO 75",
  "Armoire Haute à cloisons – 401",
  "Armoire Haute à Rideaux – 202/DLR",
  "Armoire haute sur piètements – 501",
  "Armoire Métallique Haute – 201",
  "Armoire Métallique Haute – 202",
  "Armoire pour PC",
  "Armoire RIA",
  "Armoire vitrée à 2 portes",
  "Armoire vitrée à une porte",
  "Articulation de genou",
  "Asservissement de Vitesse",
  "Autoclave électrique",
  "Bac à dissection Blanc",
  "Bac à Fiches 1 Rangée – 304",
  "Bac à Fiches 2 rangées – 305",
  "Bac à Fiches 3 Rangées – 306",
  "Baguette aimantée",
  "Bain marie à éclairage led",
  "Bain-marie à cuve inox",
  "Balance 150g/0,01 avec paravent intégré OHAUS TA152",
  "Balance analytique AS 220.R2 PLUS",
  "Balance Baxtran 60Kg – 20g",
  "Balance de précision PS 1000.R2",
  "Balance de précision WLC 2/A2/C/2",
  "Balance de précision WLC 20/A2",
  "Balance de précision WLC 6/F1/K",
  "Balance Électronique 1.2Kg – 0.1g",
  "Balance Électronique 2Kg – 1g",
  "Balance Electronique Lever 300g/0.01",
  "Balance ROBERVAL 2kg",
  "Balances de poche",
  "Balances de précision Nimbus",
  "Balances de précision portables HIGHLAND",
  "Balances DSC BAXTRAN 3Kg – 0.1g",
  "Balances/ Dynamomètres électroniques",
  "Ballon fond plat 100 ml BOMEX",
  "Ballon fond plat 100 ml Col Etroit DURAN",
  "Ballon fond plat 100 ml col long GG17",
  "Ballon fond plat 100 ml Col rodé 29/32 GLASSCO",
  "Ballon fond plat 100 ml Col Rodé 29/32 NOVACHIM",
  "Ballon fond plat 100 ml SIMAX",
  "Ballon fond plat 1000 ml Col étroit DURAN",
  "Ballon fond plat 1000 ml col étroit SIMAX",
  "Ballon fond plat 1000 ml col long GG17",
  "Ballon fond plat 1000 ml Col rodé 29/32 GLASSCO",
  "Ballon fond plat 250 ml BOMEX",
  "Ballon fond plat 250 ml Bord renforcée DURAN",
  "Ballon fond plat 250 ml Col Etroit DURAN",
  "Ballon fond plat 250 ml col long",
  "Ballon fond plat 250 ml Col long GG-17",
  "Ballon fond plat 250 ml Col Rodé 29/32 NOVACHIM",
  "Ballon fond plat 250 ml Col rodé 29/32 QUICKFIT",
  "Ballon fond plat 250 ml SIMAX",
  "Ballon fond plat 50 ml Col rodé",
  "Ballon fond plat 500 ml Bord renforcée BOMEX",
  "Ballon fond plat 500 ml Bord renforcée GG17",
  "Ballon fond plat 500 ml Col étroit GG-17",
  "Ballon fond plat 500 ml col étroit SIMAX",
  "Ballon fond plat 500 ml col large BOMEX",
  "Ballon fond plat 500 ml col long Bord renforcée GG17",
  "Ballon fond plat 500 ml Col long BORO 3.3",
  "Ballon fond plat 500 ml Col rodé 29.32 BORO3.3",
  "Ballon fond plat 500 ml Col Rodé 29/32 NOVACHIM",
  "Ballon fond plat 500 ml PYREX",
  "Ballon fond rond 1000 ml Col rodé 29/32 GLASSCO",
  "Ballon fond rond 25 ml Col Rodé 14/23 NOVACHIM",
  "Ballon fond rond 250 ml BOMEX",
  "Ballon fond rond 250 ml Col étroit PYREX",
  "Ballon fond rond 250 ml DURAN",
  "Ballon fond rond 50 ml Col Rodé 14/23 NOVACHIM",
  "Banc d’essai de Flexion",
  "Banc d’essai de Torsion",
  "Banc d’essai de Traction",
  "Banc de jardin 120cm",
  "Banc de jardin 160cm",
  "Banc Nova",
  "Banc Optique Pour Les Collèges : OPTI-BASIC®",
  "Banc Porte Manteau Double",
  "Banc porte manteau simple",
  "Banc simple sans dos",
  "Bandelettes test",
  "Banquette simple avec dos",
  "Banquette simple sans dos",
  "Baromètre Anéroïde",
  "Baromètre de toricelli",
  "Baroscope À Liquide",
  "Barreaux aimanté cylindriques 15*6mm",
  "Barreaux aimanté cylindriques 15*8mm avec anneau",
  "Barreaux aimanté cylindriques 20*7mm",
  "Barreaux aimanté cylindriques 30*8mm",
  "Barreaux aimanté cylindriques 30*8mm avec anneau",
  "Barreaux aimanté cylindriques 35*6mm",
  "Barreaux aimanté cylindriques 40*8mm",
  "Barrière de sécurité",
  "Bavette – Masques Chirurgicaux Jetables 3 Plis",
  "Bec Bunsen",
  "Bec Bunsen avec veilleuse",
  "Bec électrique QH7639",
  "Bec électrique Sérénit",
  "Bec électrique TECHNIBEC",
  "Bec Meker – Bec Bunsen",
  "Becher 100 ml ARCO",
  "Becher 100 ml EISCO",
  "Becher 100 ml GLASSCO",
  "Becher 1000 ml EISCO",
  "Becher 1000 ml en PP sans manche",
  "Becher 1000 mL en verre borosilicaté",
  "Bécher 1000ml PP",
  "Becher 2000 ml DURAN SCHOTT",
  "Becher 250 ml EISCO",
  "Becher 250 ml en PP sans manche",
  "Becher 250 ml GLASSCO",
  "Bécher 250ml PP",
  "Becher 50 ml EISCO",
  "Becher 500 mL EISCO",
  "Becher 500 ml en PP sans manche KARTELL",
  "Bécher 500ml PP",
  "Becher 600 ml GLASSCO",
  "Bécher PP 500ml",
  "Becs de chauffage type bunsen sans veilleuse",
  "Becs électriques PYROMAXI",
  "Becs électriques PYROMICO",
  "Benne",
  "Bobine À Induction",
  "Boite de pétri en PP lot de 20 Ø 85",
  "Boite de pétri en verre Ø 60",
  "Boite de pétri en verre Ø 80",
  "Boîte De Rangement Pour Lame De Microscope",
  "Boîte de résistances – 10 x 1Ω",
  "Boîte Expérimentale de Séquenceur Électronique",
  "Boîte Pharmacie",
  "Boussole avec couvercle et blocage de l’aiguille",
  "Boussole de marche SILVA",
  "Boussole Des Tangentes",
  "Boussole Projectable LD0203.2",
  "Boussole simple élève",
  "Bouteille 1000 ml en verre brun avec bouchon",
  "Bouteille 150 ml en verre brun avec bouchon",
  "Bouteille 250 ml en verre brun avec bouchon",
  "Bouteille 500 ml en verre brun avec bouchon",
  "Bouteille PE blanche 1L",
  "Brûleur LaboGaz",
  "Bureau d’accueil ISSIMO",
  "Bureau de direction BRAVA",
  "Bureau de direction CASTLE avec Retour",
  "Bureau de direction COMPACT",
  "Bureau de direction EKKO",
  "Bureau de direction EPSILON",
  "Bureau de direction FRENEL",
  "Bureau de direction JAX",
  "Bureau de Direction JHIN",
  "Bureau de direction LAURCAS",
  "Bureau de direction LEONA",
  "Bureau de direction MITO",
  "Bureau de direction PLENZO",
  "Bureau de direction PYKE",
  "Bureau de direction SYNDRA",
  "Bureau de maître Classic",
  "Bureau de maître Nova",
  "Bureau individuel BRAVA",
  "Bureau individuel CASTLE",
  "Bureau individuel EKKO",
  "Bureau individuel EZRA",
  "Bureau individuel ISSIMO",
  "Bureau individuel KAYZA",
  "Bureau individuel QUINN",
  "Bureau Laura",
  "Bureau-bibliothèque Fénon",
  "Burette 25 ml classe A Clé droit en teflon EISCO",
  "Burette 50 ml classe A Clé droit en teflon EISCO",
  "Burette 50 ml classe B robinet détachable PP avec clé PTFE GLASSCO",
  "Burette graduée 25 ml sans robinet MC CLASSE A",
  "Burette graduée 25 ml sans robinet MC CLASSE B",
  "Câble d’extension alimentaire",
  "Cable USB-01",
  "Caisse MACROPUS",
  "Caisse MACROPUS+",
  "Caisse MACROPUS+ Classique",
  "Caisse MACROPUS+ CT2T",
  "Calcium Metal 98%",
  "Capsule À Bec",
  "Capsule en céramique avec bec verseur Ø 96mm H 35mm Assistent",
  "Capsules À Bec En Verre",
  "Casier à 6 cases – 107",
  "Casier à 9 cases – 108",
  "Cavalier Banc Optique",
  "Cellule électrolytique",
  "Centrifugeuse à main",
  "Centrifugeuse à vitesse réglable, pour 8 tubes",
  "Centrifugeuse angulaire",
  "Cerveau Démontable",
  "Chaise Alpha",
  "Chaise Classique",
  "Chaise de direction ATLANTA",
  "Chaise de direction BASTIA",
  "Chaise de direction CONCORD",
  "Chaise de diréction FOCUS",
  "Chaise de direction TIZANO",
  "Chaise Opérateur BIP ROULANT",
  "Chaise Opérateur ERGO Avec Accoudoir",
  "Chaise Opérateur ISO",
  "Chaise Opérateur ROULETTE",
  "Chaise Opérateur ZODIAC",
  "Chaise Siriani",
  "Chaise Visiteur ARCHITECTE",
  "Chaise Visiteur BANQUETTE",
  "Chaise Visiteur ISO",
  "Chaise Visiteur JOLLY",
  "Chaise Visiteur MILANO",
  "Chaise Visiteur SIGMA",
  "Chariot Conteneur en fil gerbage",
  "Chariot de soin",
  "Chariot de transport en fil métallique",
  "Chauffe ballon 250mL HME-I",
  "Chauffes-ballons régulés",
  "Checktemp®4 Temperature Tester for dairy products EN 13485 certified",
  "Checktemp®4 Testeur de température",
  "Chloroform extrapure 99%",
  "Chlorure de magnésium 500g",
  "Chronomètre mécanique à aiguilles",
  "Circuit Circulaire",
  "Circuit Courant Rectiligne LD0204.1",
  "Circuit Droit",
  "Circuit Solénoïde",
  "Circuit Solénoïde 3B",
  "Circuit Solénoïde LD0204.3",
  "Ciseaux Fort",
  "Citric Acid Anhydrous",
  "Classeur 2 tiroirs – E2T",
  "Classeur métallique 2 tiroirs – 303",
  "Classeur métallique 3 tiroirs – 302",
  "Classeur métallique 4 tiroirs – 301",
  "Cloche à vide 200×200 SIMAX",
  "Coffre Escamatable MACROPUS",
  "Coffre fort CASTELLUM 100",
  "Coffre fort CASTELLUM 120",
  "Coffre fort CASTELLUM 150",
  "Coffre fort CASTELLUM 80",
  "Coffre fort CASTELLUM+",
  "Coffre fort CASTELLUM+ 4C",
  "Coffre fort CLYPEUM 11",
  "Coffre fort CLYPEUM 22",
  "Coffre fort CLYPEUM SP",
  "Coffre fort CLYPEUM+ 1",
  "Coffre fort CLYPEUM+ 2",
  "Coffre fort Hotel Quaestor COMBILOCK",
  "Coffre fort Hotel Quaestor COMPACT",
  "Coffre fort Hotel Quaestor LAPTOP",
  "Coffre fort Hotel Quaestor MOTORISÉE",
  "Coffre fort Quaestor + 350",
  "Coffre fort Quaestor + 720 Special",
  "Coffre fort Quaestor 1",
  "Coffre fort Quaestor 11",
  "Coffre fort Quaestor 2",
  "Coffre fort Quaestor 22",
  "Coffre fort Quaestor 3",
  "Coffre fort Quaestor 33",
  "Coffre fort Quaestor 4",
  "Coffre fort Quaestor 44",
  "Coffre fort Quaestor 5",
  "Coffre fort Quaestor 5 +",
  "Coffre fort Quaestor 6",
  "Coffre fort Quaestor Hotel MOTORISÉE",
  "Coffre fort Quaestor MINI",
  "Coffre fort Quaestor+ 420",
  "Coffre fort Quaestor+ 720",
  "Coffre fort Quaestor+ 720 SLIM",
  "Coffret chimie organique",
  "Coffret Mini-laser Optique Ondulatoire",
  "Coffret seconde",
  "Collection compacte 50 atomes",
  "Collection hydrocarbures",
  "Collection orbitales 59 atomes",
  "Collection Organique 100 Atomes",
  "Collection organique 104 atomes",
  "Collection organique 161 atomes",
  "Collection organique 54 atomes",
  "Collection Organique 85 Atomes",
  "Colonne à compartiments – TURRIM",
  "Colorimètre PIERRON MT13230",
  "Commutateur Bipolaire",
  "Conductimètre et TDS/Salinité Mètre de Laboratoire edge® – HI2003",
  "Conductimètre et TDS/Salinité Mètre Edge® – HI2003",
  "Cônes d’étanchéité Caoutchouc",
  "Cônes pour micropipettes",
  "Cordon pour électrodes",
  "Cordons Standards À Reprise Arrière",
  "Couvercles pour bain marie",
  "Crachoir 60ml bouchon Rouge",
  "Creuset de laboratoire en céramique avec bec verseur Ø 43mm H 70mm",
  "Creuset en céramique à fond épais Ø 30mm H 30mm",
  "Creuset en céramique à paroi épaisse Ø 25mm H 25mm",
  "Cristallisoir 1000 ml avec bec verseur NOVACHIM",
  "Cristallisoir 300 ml avec bec verseur NOVACHIM",
  "Cristallisoir 3000 ml avec bec verseur DURAN SCHOTT",
  "Cristallisoir 500 ml avec bec verseur",
  "Cristallisoir 500 ml sans bec verseur",
  "Cuve 2,5 L pour bain marie ci-dessus",
  "Cuve à Electrolyse",
  "Cuve à faces parallèles",
  "Digital Flat Tip pH Electrode for Food Surfaces",
  "Dispositif d’OERSTED",
  "Dispositif Etude Vide",
  "Distillateur inox/verre",
  "Dosage colorimétrique du ph",
  "Dosage oxygène dissous",
  "Dynamomètre 10N/0,1N",
  "Dynamomètre 1N/0,05N",
  "Dynamomètre 5N/0,1N",
  "Dynamomètre Droit 5N/0,1N",
  "Dynamomètre Droit 5N/0,1N/500g",
  "Eau Distilée",
  "Eau Iodée 100mL",
  "Eau Purifée",
  "Égouttoir mural ou de paillasse avec bac",
  "Électrode de Conductivité Numérique – HI763100",
  "Électrode de pH à corps mince pour produits laitiers – FC250B",
  "Électrode de pH à pointe de lance pour semi-solides – HI2031B",
  "Électrode De Ph Alimentaire Pour Fromage Avec Corps En Acier Inoxydable Et Connecteur Quick Connect DIN",
  "Électrode de pH au yogourt Foodcare - FC2133",
  "Électrode de pH avec pointe conique et connecteur BNC",
  "Électrode de pH corps en PVDF Foodcare pour produits laitiers et aliments semi-solides",
  "Electrode de pH FoodCare pour produits laitiers et aliments semi-solides avec connecteur DIN à connexion rapide – FC2023",
  "Electrode de pH numérique Corps en PVDF Foodcare pour produits laitiers FC2020",
  "Électrode de pH numérique pour semi-solides et émulsions – HI10530",
  "Electrode de pH pour corps en verre numérique pour usage général HI11310",
  "Électrode de pH pour les mesures directes de fromage  – FC242D",
  "Electrode de pH PVDF pour produits laitiers – FC100B",
  "Electrode de pH rechargeable en corps de verre avec Bluetooth® HALO – HI11312",
  "Électrode de pH/température Foodcare pour le lait",
  "Électrode pH avec micro ampoule et connecteur BNC – HI1083B",
  "Électrode pH combinée rechargeable avec connecteur BNC – HI1131B",
  "Électrode ph edge",
  "Électrode pH Foodcare avec corps en acier inoxydable de petit diamètre et connecteur BNC",
  "Électrode pH Foodcare pour produits laitiers – FC202D",
  "Électrode pH Foodcare pour yaourt  – FC213D",
  "Électrode pH polypropylène",
  "Electrode pH pour crèmes, sauces et jus de fruits  – FC220B",
  "Electrode pH pour mesures directes dans le fromage  – FC2423",
  "Électrode pH pour produits laitiers  – FC2100",
  "Électrode pH pour semi-solides  – FC200S",
  "Électrode pH pour yaourt et crèmes  avec connecteur BNC – FC210B",
  "Électrode sélective d’ions à demi-cellule pour potassium  – HI4014",
  "Electrode sélective ionique combinée de sodium  – FC300B",
  "Électrodes charbon",
  "Électrodes en plaques",
  "Électrodes ph époxy",
  "Électrolyseur Nickel",
  "Électrolyseur en U",
  "Électrolyseur en U sur suport en MDF",
  "Électroscope",
  "Élément de classement rotatif – ERA5",
  "Éléments de volta",
  "Enregistreur de Température étanche HI148-1",
  "Enregistreur de Température HI144-10",
  "Enregistreur de température HI148-2",
  "Enregistreur de Température HI148-3",
  "Enregistreur de Température HI148-4",
  "Ensemble analyse de l’eau",
  "Ensemble Cuve Demi-cylindrique",
  "Ensemble Moteur-Génératrice 1,5/4,5V",
  "Ensemble Pendule Élastique",
  "Ensemble Réflexion-réfraction",
  "Entonnoir à poudre Ø 50",
  "Entonnoir à poudre Ø 80",
  "Entonnoir en PP 100mm",
  "Entonnoir en PP 50mm",
  "Entonnoir en PP 75mm",
  "Entonnoir en verre Ø 100 EISCO",
  "Entonnoir en verre Ø 75 EISCO",
  "Entonnoir Ø 50 en verre",
  "Eprouvette à base hexagonale 1000ml PP",
  "Eprouvette à base hexagonale 100ml PP",
  "Eprouvette à base hexagonale 250ml PP",
  "Eprouvette à base hexagonale 500ml PP",
  "Eprouvette à base hexagonale 50ml PP",
  "Eprouvette graduée 1000 ml Classe A Base ronde EISCO",
  "Eprouvette graduée 1000 ml Classe A Base ronde MINGHE",
  "Eprouvette graduée 100ml classe B basse Hexagonal ASSISTENT",
  "Eprouvette graduée 100ml classe B basse ronde",
  "Eprouvette graduée 100ml classe B basse ronde BOMEX",
  "Eprouvette graduée 100ml classe B basse ronde MC",
  "Eprouvette graduée 100ml classe B basse ronde MINGHE",
  "Eprouvette graduée 250ml classe B basse ronde BOMEX",
  "Eprouvette graduée 250ml classe B basse ronde MINGHE",
  "Eprouvette graduée 25ml Classe A Pied Plastique",
  "Eprouvette graduée 25ml classe B basse Hexagonale ASSISTENT",
  "Eprouvette graduée 25ml classe B basse ronde KELSUN",
  "Eprouvette graduée 25ml classe B basse ronde MINGHE",
  "Eprouvette graduée 60ml classe B basse Hexagonal ASSISTENT",
  "Eprouvette graduée, 100 ml – Classe A – Base hexagonal – BORO3.3",
  "Eprouvette graduée, 100 ml – Classe A – Base ronde – EISCO",
  "Eprouvette graduée, 250 ml – Classe A – Base ronde – EISCO",
  "Eprouvette graduée, 50 ml – Classe A – Base ronde – EISCO",
  "Eprouvette graduée, 500 ml – Classe A – Base ronde – EISCO",
  "Erlenmeyer 100 ml",
  "Erlenmeyer 100 ml 95",
  "Erlenmeyer 100 ml en verre borosilicaté EISCO",
  "Erlenmeyer 1000 ml  DURAN SCHOTT",
  "Erlenmeyer 1000 ml  BOMEX",
  "Erlenmeyer 1000 ml  DURAN SCHOTT",
  "Erlenmeyer 1000 ml DURAN SCHOTT",
  "Erlenmeyer 1000 ml en verre borosilicaté EISCO",
  "Erlenmeyer 1000 ml Novachim",
  "Erlenmeyer 125 ml PYREX",
  "Erlenmeyer 150 ml BOMEX",
  "Erlenmeyer 2000 ml  DURAN SCHOTT",
  "Erlenmeyer 25 ml CHEMIL",
  "Erlenmeyer 250 ml",
  "Erlenmeyer 250 ml",
  "Erlenmeyer 250 ml en verre borosilicaté EISCO",
  "Erlenmeyer 50 ml",
  "Erlenmeyer 50 ml  DURAN SCHOTT",
  "Erlenmeyer 50 ml BORO 3.3",
  "Erlenmeyer 50 ml Novachim",
  "Erlenmeyer 500 ml  BORO 3.3",
  "Erlenmeyer 500 ml  GLASSCO",
  "Erlenmeyer 500 ml  SIMAX",
  "Erlenmeyer 500 ml  GG17",
  "Erlenmeyer 500 ml  DURAN SCHOTT",
  "Erlenmeyer 500 ml en verre borosilicaté EISCO",
  "Erlenmeyer 500 ml Novachim",
  "Erlenmeyer 500 ml SIMAX",
  "Escabeau à 2 marches en époxy",
  "Établi d’atelier – EA2T",
  "Ethanol Absolute",
  "Etude De La Modulation Et La Demodulation D’amplitude",
  "Étuve universelle",
  "Évaporateur rotatif",
  "Feuilles d’aluminium",
  "Fichier à 2 tiroirs – F2T",
  "Fiole à Vide 1000mL Novachim",
  "Fiole jaugée 10ml classe A avec bouchon EISCO",
  "Fiole jaugée 10ml classe A avec bouchon Novachim",
  "Fiole jaugée 2000ml classe B avec bouchon GG17",
  "Fiole jaugée 200ml classe A avec bouchon Novachim",
  "Fiole jaugée 250ml classe A avec bouchon",
  "Fiole jaugée 250ml classe A avec bouchon Glassco",
  "Fiole jaugée 250ml classe A MBL",
  "Fiole jaugée 25ml classe A avec bouchon EISCO",
  "Fiole jaugée 500ml classe A avec bouchon ARCO",
  "Fiole jaugée 50ml classe A avec bouchon",
  "Fiole jaugée 50ml classe A avec bouchon EISCO",
  "Fiole jaugée 50ml classe A avec bouchon Novachim",
  "Fiole jaugée 5ml classe A avec bouchon GLASSCO",
  "Flacon laveur 250 ml 29/32 NORMAX",
  "Flacon pour dosage oxygène dissous",
  "Flacon réactif 250mL avec vis GL45 SIMAX",
  "FNIRSI DSO-PRO Oscilloscope",
  "Formol – Formaldehyde 30% Vol – 1L",
  "Fréquencemètre FJ-2",
  "Gants anti-chaleur 100°C",
  "Gants de chimie en NITRILE",
  "Gants LATEX non stérile",
  "Gants LATEX stérile",
  "Gants NITRILE",
  "Générateur Base Fréquence GBF SG1638N",
  "Générateur de signaux arbitraires / Fonctions Hantek HDG2012B",
  "Générateur de Tension Continue LD0614.3",
  "Générateur de tensions variable",
  "Générateur De VAN DE GRAAFF",
  "Goupillon 12mm",
  "Goupillon 27mm",
  "Hémisphères de Magdebourg",
  "HYDROMAX 100 bain-marie thermostaté numérique",
  "Hydroxide de Sodium 97%",
  "Hygromètre métallique mural",
  "Inductance variable 1,1 H : VARIASELF® 2",
  "Inductance Variable LD0704",
  "Interrupteur mono polaire à levier",
  "Interrupteur mono polaire à levier",
  "Interrupteur monopolaire à levier LD0705",
  "Interrupteur simple",
  "Interrupteur simple 3B",
  "IPA Isopropanol – 2-propanol",
  "Jeu 3 Dynamomètre Circulaire 1N/2N/5N",
  "Jeu De 2 Ressorts À Spires Non Jointives",
  "Kit complet robot 2 roues 2WD",
  "Kit électrochimie",
  "Kit Électrostatique",
  "Kit Modele Anatomique",
  "Lame en acier inoxydable pour testeurs de pH de la viande, compatible avec HI9810452 et HI981045",
  "Lame paquet de 50",
  "Lamelle paquet de 100",
  "Lampe à alcool en verre + mèche",
  "Lampe à vis E10 12V 0.33A",
  "Lampe à vis E10 2.5V 0.3A",
  "Lampe à vis E10 6V 0.5A",
  "Lampe Optique HALOGEN 64640 HLX",
  "Lanterne de laboratoire 21W – 12V",
  "Laser Multidirectionnel",
  "Laser Rouge",
  "Laser Rouge mini",
  "Laser Vert",
  "Laser Vert Pour L’élève",
  "Lentille Demi-circulaire",
  "Lentilles Demi-cylindre en Plexiglass",
  "Lentilles En Verre Biconcave – Biconvexe",
  "Lit Simple",
  "Lit Superposé en litière en bois",
  "Lit Superposé en métal",
  "Lit Surélevé",
  "Loupe À Main Ø 40mm",
  "Loupe À Main Ø 50mm",
  "Loupe À Main Ø 60mm",
  "Loupe À Main Ø 78mm",
  "Loupe binoculaire x20",
  "Loupe Monoculaire x20",
  "Lunettes de sécurité",
  "Manomètre À Eau",
  "Maquette de muscle",
  "Mesureur de vitesse MESURA®",
  "Mètre pliant en bois",
  "Mètre ruban Souple 150cm – 60in",
  "Meuble 3 Niches",
  "Meuble 6 Places 3 Niches",
  "Meuble 18 Compartiments",
  "Meuble 2 Niches",
  "Meuble 4 Places 2 Niches",
  "Meuble 6 Niches",
  "Meuble 6 Places 2 Niches + Portes",
  "Meuble 9 Compartiments",
  "Meuble Présentoir de livres",
  "Meuble sous Paillasses 1 Porte",
  "Meuble sous Paillasses 1 Tiroir 1 Porte",
  "Meuble sous Paillasses 1 Tiroir 2 Portes",
  "Meuble sous Paillasses 2 Portes",
  "Meuble sous Paillasses 2 Tiroirs",
  "Meuble sous Paillasses 3 Tiroirs",
  "Meuble sous Paillasses 4 Tiroirs",
  "Meuble sous Paillasses métallique 5 Tiroirs",
  "Micro brûleur",
  "Microscope collège x400",
  "Microscope collège x400 LED",
  "Microscope collège x600 pour étudiants",
  "Microscope Led FT10X",
  "Microscope Monoculaire 40-1 000",
  "Microscope x600",
  "Microscope x900",
  "Mini agitateur magnétique – HI190M",
  "Mini titrateur pour mesurer l’acidité titrable dans les produits laitiers – HI84529",
  "Mini-agitateur magnétique avec couvercle en acier inoxydable – HI200M",
  "Miroir",
  "Miroir chiral",
  "Modèle anatomique : Squelette humaine",
  "Modèle anatomique : Tête humaine",
  "Modèle anatomique de cerveau humain",
  "Modèle anatomique de cœur",
  "Modèle anatomique de coeur humain",
  "Modèle anatomique de l’oeil humain",
  "Modèle anatomique de mâchoire",
  "Modèle anatomique de rein",
  "Modèle anatomique de rein humain",
  "Modèle anatomique de Tronc Humain",
  "Modèle cristallin diamant",
  "Modèle cristallin graphite",
  "Modèle cristallin NaCL",
  "Modèle d’oeil humain",
  "Modèle d’oreille",
  "Modèle de cœur 4X",
  "Modèle de respiration",
  "Modèle mâchoire dentaire",
  "Modèle moléculaire acides aminés",
  "Modèle moléculaire acides nucléiques",
  "Modèle moléculaire collège",
  "Modèle moléculaire collège",
  "Modèle moléculaire compact",
  "Modèle moléculaire glucides",
  "Mortier et Pilon 220 ml",
  "Mortier et pilon 275ml",
  "Mortier et Pilon 500 ml",
  "Mortier et pilon 500ml",
  "Mortier et Pilon 900 ml",
  "Mortier et pilon 900ml",
  "Mortier et pilon en bois 900ml",
  "Multimètre Analogique Hung Chang HM102BZ",
  "Multimètre Numérique DM97",
  "Multimètre Numérique DT9205B",
  "Multimètre Numérique LD0603.2",
  "Multimètre Numérique MU88",
  "Multimètre Numérique MY64",
  "Multimètre Numérique UT33D+",
  "Multimètre Numérique UT51",
  "Multiparamètre EC Meter edge® – HI2030-02",
  "Multiparamètre Qualité Recherche de pH/Rédox et EC/TDS/Résistivité/Salinité et Température HI5521-02",
  "Multipramètre qualité recherche de PH/Rédox/ISE et EC/TDS/Résistivité/Salinité et température HI5522-02",
  "Nettoyeur à ultrasons",
  "Noix double ø 10 mm",
  "Noix double ø 16 mm",
  "Noix double ø 21 mm",
  "Noix double polyvalente",
  "Oscilloscope Analogique 20MHz – CQ5020",
  "Oscilloscope analogique bicourbe 2x20MHz – CQ620A",
  "Oscilloscope numérique UTD2052CL+",
  "Oscilloscope Portable DSO 2090",
  "Osmomètre de Dutrochet",
  "Oxygène-meter WAC-2019-SD",
  "Oxymètre",
  "Oxymètre mesura",
  "Paillasse 120 avec Dosseret en HPL",
  "Paillasse 120 sans Dosseret en HPL",
  "Paillasse 150 avec Dosseret en HPL",
  "Paillasse 150 sans Dosseret en HPL",
  "Paillasse 180 avec Dosseret en HPL",
  "Paillasse 180 sans Dosseret en HPL",
  "Paillasse Humide 120 avec Dosseret en HPL",
  "Paillasse Humide 120 sans Dosseret en HPL",
  "Paillasse Humide 150 avec Dosseret en HPL",
  "Paillasse Humide 150 sans Dosseret en HPL",
  "Paillasse Humide 180 avec Dosseret en HPL",
  "Paillasse Humide 180 sans Dosseret en HPL",
  "Panier égouttoir pour tubes à essais",
  "Papier filtre en rame 25",
  "Papier pH 0-14",
  "Passeur d’échantillons HI921",
  "pH meter Paillasse AD1000",
  "pH meter portable CA 10001",
  "pH mètre / Rédox / température portable étanche – HI991003",
  "PH mètre de fromage portable – HI99165",
  "PH mètre de fromage professionnel – HI98165",
  "pH mètre sans fil Foodcare HALO® – FC2022",
  "PH-mètre / température portable étanche – HI991001",
  "pH-mètre / Thermomètre 701047",
  "pH-mètre de banc à double entrée HI3512-02",
  "pH-mètre de Laboratoire 209J",
  "pH-mètre de laboratoire à sortie analogique",
  "PH-mètre de lait portable – HI99162",
  "PH-mètre de lait professionnel et portable – HI98162",
  "pH-mètre de paillasse",
  "Ph-metre de paillasse pH 209",
  "PH-mètre de yaourt portable – HI99164",
  "PH-mètre de yaourt professionnel – HI98164",
  "pH-mètre LUTRON PH-211",
  "pH-mètre MESURA",
  "pH-mètre multiparamètre edge® HI2020",
  "Ph-mètre portable : ph et millivoltmètre",
  "PH-mètre portable pour aliments et produits laitiers- HI99161",
  "PH-mètre portable professionnel spécial Aliments – HI98161",
  "PH-mètre sans fil pour Aliments HALO – HI10532",
  "pH-mètre Simple",
  "pH-mètre stylo économique",
  "pH-mètre stylo LUTRON PH220",
  "pH/mètre de table avec résolution de 0,01 – HI2211",
  "Photomètre et pH-mètre de paillasse multiparamètres – HI83300",
  "Photomètre pH, chlore libre et total – HI97710",
  "Photomètre Portable de Chlore Libre – HI97701",
  "Photomètre portable de chlore libre et total – HI97711",
  "Pile Daniell",
  "Pile Leclanche",
  "Pile volta",
  "Pilon en porcelaine pour mortier 100mm",
  "Pilon en porcelaine pour mortier 165mm",
  "Pince à creuset",
  "Pince à creuset courbe Inox",
  "Pince à creuset Inox manchons fibre",
  "Pince à creuset plate Inox",
  "Pince bois pour tubes à essais",
  "Pince Crocodile protégée GF",
  "Pince Crocodile protégée PF",
  "Pince de MOHR à ressort",
  "Pince double pour burette",
  "Pince droite « à Sodium »",
  "Pince en bois dur pour ballon",
  "Pince métallique pour tube essais",
  "Pince pour ballon",
  "Pince pour burette",
  "Pince Tube à essai",
  "Pince-portoir pour électrodes",
  "Pinces à 2 mâchoires avec noix de serrage",
  "Pinces à 2 mâchoires sans noix de serrage",
  "Pinces à 3 doigts avec noix de serrage",
  "Pinces à 3 doigts sans noix de serrage",
  "Pinces à 4 doigts avec noix de serrage",
  "Pinces à 4 doigts sans noix de serrage",
  "Pipette 1 ml Graduée ISOLAB",
  "Pipette 10 ml Graduée Eisco",
  "Pipette 10 ml Graduée Glassco",
  "Pipette 20 ml jaugée 1 boule Classe B",
  "Pipette 5 ml Graduée Eisco",
  "Pipette Pasteur 3ml lot 250 piéces",
  "Pipette Sterile 25ml Sous Sachet 25ml",
  "Pipette Sterile 5ml 1/10 Ml Sterilin",
  "Pipteur à piston 10ML",
  "Pipteur à piston 25ML",
  "Pipteur a piston 2ML",
  "Pissette 1000ml PE",
  "Pissette 250mL",
  "Pissette 250ml PE",
  "Pissette 500mL",
  "Pissette 500ml PE",
  "Plaque chauffante 1 feu",
  "Plaque chauffante 135",
  "Plaque de manipulation pour la microbiologie",
  "Plaque pour combustion",
  "Plaque pour combustion des poudres métalliques",
  "Plaque pour la combustion des solides",
  "Platine d’essai – Bread Board 840 Lite",
  "Platine migration ions",
  "Platine Pour Le Vide Avec 2 robinets",
  "Platine Pour Le Vide Avec Raccords Électriques",
  "Plexiglass thermopliable 2mm",
  "Plexiglass thermopliable 3mm",
  "Pluviomètre",
  "Poire propipette",
  "Pont De Diodes Électroluminescentes Sur Support : DIDALED®",
  "Pool Line ORP / Testeur de température – HI981204",
  "Pool Line Testeur de pH de poche pHep® – HI981074",
  "Porte Blindée – CUSTOS",
  "Porte manteau 5 patères",
  "Porte manteau ISO",
  "Porte manteau ISO",
  "Porte-pipettes en plastique abs",
  "Portoir égouttoir pour pipettes",
  "Portoir en bois pour pipettes",
  "Portoir en inox pour tubes à essais",
  "Portoir pour tubes à essais",
  "Poste de qualité – PTR",
  "Poste de travail  a une étagere en HPL",
  "Poste de travail fixe",
  "Potassium Dihydrogen Orthophosphate 99%",
  "Potomètre de coutable",
  "Poubelle métallique",
  "Préparation microscopique",
  "Pyridine 98%",
  "Rails de LAPLACE",
  "Rangement BASSE SLIDE",
  "Rangement HAUT 2 PORTES",
  "Rangement HAUTE MIXTE 2 PORTES",
  "Rangement HAUTE OUVERTE UNIE",
  "Rangement MI-HAUTE 2 PORTES",
  "Rangement Modulaire a 12 tiroirs",
  "Rayonnage Leger",
  "Rayonnage Mi-Lourd",
  "Réactifs de chlore total  HI93711-01",
  "Réactifs de chlore total  HI93711-03",
  "Réfractomètre numérique HI96821",
  "Réfractomètre numérique pour l’analyse de brix dans les aliments – HI96801",
  "Réfractomètre numérique pour l’analyse du sucre dans l’industrie alimentaire – HI96800",
  "Régulateur de température",
  "Resistance de recharge pour distillateur en verre",
  "Ressorts à spires Jointives ⌀13.8",
  "Ressorts à spires Jointives ⌀9.8",
  "Rhéostat 100Ω – 1.8A",
  "Rhéostat 333Ω – 1.4A",
  "Rhéostat 3B 10Ω – 6A",
  "Rhéostat 3B 23Ω – 5A",
  "Rhéostat 3B 333Ω – 1A",
  "Rhéostat 3B 33Ω – 3.1A",
  "Rhéostat Jinling 23Ω – 5A",
  "Rhéostat MCP 10Ω – 5.6A",
  "Rhéostat MCP 11Ω – 8A",
  "Rhéostat MCP 23Ω – 5A",
  "Rhéostat MCP 333Ω – 0.95A",
  "Roll conteneur – 2 côtés",
  "Rosace 2 Personnes CLOSED",
  "Rosace 2 Personnes OPEN",
  "Rosace 4 Personnes",
  "Rosace 6 Personnes",
  "Roue de Barlow",
  "Sablier Sable Blanc",
  "Sablier Sable Blue",
  "Série de poids en laiton",
  "Servante d’atelier SA1",
  "Servante d’atelier SA2P-3T",
  "Simulateur Logique IS-MLCS1",
  "Sodium tetraborate 99%",
  "Solénoïde Multispires",
  "Solution 79 : Tableau Interactif StarBoard FX-79E2 + Vidéoprojecteur DW275",
  "Solution 89 : Tableau Interactif StarBoard FX-89WE2 + Vidéoprojecteur DW275",
  "Solution 89 : Tableau Interactif StarBoard FX-89WE2 + Vidéoprojecteur DW284-ST",
  "Solution d’étalonnage 100% NaCl pour les mesures de salinité de l’eau de mer  – HI7037L",
  "Solution d’étalonnage de pompe pour l’acidité titrable dans le mini-titrateur pour produits laitiers – HI84529-55",
  "Solution d’étalonnage pH 1.68  – HI7001L",
  "Solution d’étalonnage pH 10,01  HI7010L",
  "Solution d’étalonnage pH 4,01 en Sachets  – HI70004P",
  "Solution d’étalonnage pH 7,01 en Sachets  – HI70007P",
  "Solution d’étalonnage Redox @ 25°C 470 mV  – HI7022L",
  "Solution d’étalonnage Redox 240 mV  – HI7021L",
  "Solution d’étalonnage standard de conductivité 12880 µS/cm  HI7030L",
  "Solution d’étalonnage standard de conductivité 1413 µS / cm  HI7031L",
  "Solution d’étalonnage standard de conductivité 5000 µS/ cm  HI7039L",
  "Solution d’étalonnage standard de conductivité 80000 µS/cm – HI7034L",
  "Solution d’étalonnage TDS à 1382 mg / L  – HI7032L",
  "Solution de nettoyage d’électrode de pH à usage général  HI7061L",
  "Solution De Nettoyage Et De Désinfection Pour Produits Laitiers",
  "Solution de nettoyage pour dépôts de fromage  – HI700642P",
  "Solution de nettoyage pour dépôts de lait  – HI700640P",
  "Solution de nettoyage pour les dépôts de fromage  – HI70642L",
  "Solution de nettoyage pour les dépôts de yogourt  – HI70643L",
  "Solution de nettoyage pour les produits laitiers – HI70640L",
  "Solution de nettoyage pour les produits laitiers – HI70641L",
  "Solution de remplissage d’électrolyte 1M KNO₃ – HI7072L",
  "Solution de remplissage d’électrolyte, 3,5 M KCl + AgCl  – HI7071",
  "Solution de Titrage pour le mini titrateur de produits laitiers Gamme étroite 50 – HI84529-52",
  "Solution étalon standard de Conductivité – HI7035L",
  "Solution étalons Standards de chlore libre et total CAL Check™ HI97701-11",
  "Solution Nettoyante Pour Dépôts De Yaourt",
  "Solution Tampon PH 7",
  "Sonde à Thermocouple De Type K à Pénétration Ultra-Rapide Avec Poignée Foodcare",
  "Sonde à thermocouple de type K HI766E1",
  "Sonde De Pénétration Alimentaire, Usage Général",
  "Sonde de pénétration Foodcare",
  "Sonde de PH-201",
  "Sonde De Température En Acier Inoxydable Avec Connecteur Phono",
  "Sonde de thermocouple à pénétration - FC767C1",
  "Sonde de thermocouple de type T avec poignée – FC767PW",
  "Sonde en acier inoxydable avec capteur exposé Foodcare",
  "Sonde filaire conçue pour l’immersion dans un liquide",
  "Sonde pour réservoirs Foodcare, récipients et cuves",
  "Source Lumineuse DUOLUMEN®",
  "Spatule cuillère double 155mm",
  "Spatule double 220mm fine inox",
  "Spatule double cuillere-lame micro 155mm",
  "Spatule double Cuilliere Nickel 150mm",
  "Spatule double Cuilliere Nickel 200mm",
  "Spatule double Cuilliere Nickel 250mm",
  "Spectrophotomètre iris – HI801",
  "Squelette Humain 85",
  "Stéthoscope léger en acier inoxydable",
  "Stroboscope Électronique",
  "Support 10 tubes a essai en bois avec egouttoir",
  "Support 12 tubes a essai en bois",
  "Support 32 tubes a essai métallique",
  "Support 60 tubes a essai en PP",
  "Support 66 tubes a essai en PP",
  "Support Ampoule à décanter",
  "Support de lampe à vis E10",
  "Support de lampe E10 double 3B",
  "Support de lampe E10 double LD0707",
  "Support élévateur 200x200mm",
  "Support en A",
  "Support Potence & Tige Acier Niklé EISCO",
  "Support Potence 185mmx120mm & Tige Acier",
  "Support Potence 205mmx130mm & Tige Acier",
  "Support Potence 220mmx140mm & Tige Acier",
  "Support Pour Lampe À Alcool",
  "Support pour portoir",
  "Support Statif Avec Socle En A",
  "Support statif double pour ampoules à décanter et entonnoirs",
  "Support statif pour burettes ou colonnes",
  "Support statif SYSDIDAC®",
  "Support statif universel",
  "Support trépied anneau 140 mm",
  "Support tube a essai en inox à 36 emplacements",
  "Table Biplaces Degla",
  "Table Biplaces ISO",
  "Table Biplaces Monaco",
  "Table de Réfectoire Rectangulaire",
  "Table de réunion CARRÉE CHALLENGE",
  "Table de réunion KAYZA",
  "Table de réunion LAURCAS",
  "Table de réunion QUINN",
  "Table de soin",
  "Table de travail",
  "Table Hexagonale",
  "Table Monobloc Biplaces",
  "Table Monobloc Monoplace",
  "Table Monoplace Degla",
  "Table Monoplace ISO",
  "Table Monoplace Monaco",
  "Table Octogonale",
  "Table Rectangulaire",
  "Table Ronde",
  "Table TECHNIBEC microbiologie",
  "Table Trapèze 120cm",
  "Table Trapèze 90cm",
  "Tableau affichage mural",
  "Tableau Ardoisine",
  "Tableau blanc magnétique",
  "Tableau de conférence",
  "Tableau interactif StarBoard FX-79WE2",
  "Tableau interactif StarBoard FX-89WE2",
  "Tableau pivotant sur pieds deux faces",
  "Tabouret avec Repose pied",
  "Teslamètre Matelco 6736",
  "Teslamètre MCP TM204",
  "Teslamètre numérique",
  "Teslamètre T100",
  "Testeur de pH de la viande avec électrode spécialisée intégrée-HI981045",
  "Testeur de pH de lait HI981034",
  "Testeur de pH humidité du sol 3in1",
  "Testeur de pH sans fil HALO2 pour le lait",
  "Testeur de pH sans fil HALO2 pour viande avec électrode spécialisée intégrée-HI9810452",
  "Testeur pH/EC/TDS/°C, 20,00 mS 10,00 g/L – HI98130",
  "Testeur pH/EC/TDS/°C, 3999 µS 2000 mg/L – HI98129",
  "Testeurs TDS et EC étanches – HI983044",
  "Têt de combustion Ø 43mm H 24mm",
  "Têt de combustion Ø 62mm H 30mm",
  "Thermomètre à Alcool -10°C / 110°C",
  "Thermomètre à Alcool 0°C / 110°C",
  "Thermomètre à Mercure -10°C / 110°C",
  "Thermomètre à thermistance Foodcare – HI93501",
  "Thermomètre à thermocouple de type K – HI935005",
  "Thermomètre à thermocouple de type K – HI935007",
  "Thermomètre à thermocouple de type K Foodcare avec sonde interchangeable",
  "Thermomètre à thermocouple de type K HI9350011",
  "Thermomètre à thermocouple de type T – HI9350041",
  "Thermomètre À Thermocouple De Type T Foodcare Avec Sonde Fixe",
  "Thermomètre Celsius en forme de T  HI145-00",
  "Thermomètre Celsius en forme de T",
  "Thermomètre Checkfridge™ à capteur à distance spécial frigidaire HI147-00",
  "Thermomètre de précision avec sonde déportée – HI98509",
  "Thermomètre mini / maxi  +/-1°c",
  "Thermomètre Mural -30°C / +60°C",
  "Thermomètre Mural -50°C / +50°C",
  "Thermomètre Numérique LCD Avec Sonde",
  "Thermomètre numérique Nicety DT804",
  "Tige métallique statif",
  "Tiges pour statif SYSDIDAC®",
  "Titrant de gamme basse 20 pour l’acidité titrable dans le mini titrateur laitier – HI84529-50",
  "Titrant pour l’acidité titrable dans le mini titrateur de produits laitiers  – HI84529-51",
  "Titrateur potentiométrique automatique",
  "Titrateur potentiométrique automatique avancé – HI932",
  "Titreur Coulométrique Karl Fischer",
  "Titreur Volumétrique Karl Fischer",
  "Toile Métallique",
  "Trépied Métallique",
  "Triangle pour creusets",
  "Trompe à eau PP",
  "Tronc Humain Non Bisexué 85 cm",
  "Trousse à dissection",
  "Tube a essai 10*112",
  "Tube a essai 12*100",
  "Tube à essai 12*120 avec bord",
  "Tube à essai 12*120 bord evase",
  "Tube à essai 12*75",
  "Tube à essai 14*140",
  "Tube à essai 14*140 NORMAX",
  "Tube a essai 16*160",
  "Tube à essai 16*160 avec bouchon",
  "Tube a essai 16*160 avec bouchon Caoutchouc",
  "Tube a essai 16*160 avec bouchon PP",
  "Tube à essai 16*160 NORMAX",
  "Tube à essai 16*160 PYREX",
  "Tube à essai 18*150",
  "Tube à essai 18*180 avec bouchon",
  "Tube à essai 25*200",
  "Tube Centrifuge 28*160",
  "Tube en U avec tubulure inférieure 150mm",
  "Tube en U avec tubulure inférieure 190mm",
  "Tube en U avec tubulure inférieure 230mm",
  "Tube en Y en verre",
  "Tube feuille anglaise Ø 4 x 6 mm",
  "Tube feuille anglaise Ø 4 x 6 mm",
  "Tube feuille anglaise Ø 6 x 9 mm",
  "Tube feuille anglaise Ø 8 x 12 mm",
  "Tube silicone Ø 5 x 8 mm",
  "Tube silicone Ø 5 x 8 mm",
  "Tube silicone Ø 6 x 9 mm",
  "Tube silicone Ø 6 x 9 mm",
  "Tube silicone Ø 8 x 12 mm",
  "Tube silicone Ø 8 x 12 mm",
  "Tubes capillaires à un bout fermé",
  "Valet polypropylène pour ballons",
  "Verre à pied 100 ml en verre",
  "Verre à pied 1000 ml en verre ASSISTENT",
  "Verre à pied 125 ml en PP",
  "Verre à pied 500 ml en verre NORMAX",
  "Vestiaire – 101",
  "Vestiaire – 102",
  "Vestiaire – 103",
  "Vestiaire – 104",
  "Vestiaire – 105",
  "Vestiaire – 106",
  "Vestiaire – 109",
  "Vestiaire – 115",
  "Vibreur pour expérience de MELDE",
  "Vidéoprojecteur DLP Vivitek DW275",
  "Vidéoprojecteur DLP Vivitek DW284-ST",
  "Vitrine d’affichage",
  "Vitrine d’affichage magnétique",
  "Voltmètre analogique 0-10V",
  "Voltmètre Analogique AC/DC",
  "Voltmètre analogique MS-402",
  "Voltmètre Analogique SVM-001",
  "Wattmètre – Joulemètre Mesura 22022",
  "Wattmètre Numérique LD0608.4"
];
